[package]
name = "intmap"
version = "1.1.0"
edition = "2018"
description = "Specialized HashMap for u64 keys"
authors = ["Jesper Axelsson <jesperaxe@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/JesperAxelsson/rust-intmap"
keywords = ["hashmap", "u64", "intmap"]

[dependencies]
serde = { version = "1.0", optional = true, default-features = false }

[dev-dependencies]
indexmap = "1.8.2"
nohash-hasher = "0.2.0"
rand = "0.8.5"
rustc-hash = "1.1.0"

[package.metadata.docs.rs]
features = ["serde"]
